---
is_development: true

digital_collections_vault_values: "{{ lookup('community.hashi_vault.vault_kv2_get', 'digital-collections/development', engine_mount_point='kv-applications') }}"
dld_sidekiq_pro_vault_values: "{{ lookup('community.hashi_vault.vault_kv2_get', 'sidekiq_pro', engine_mount_point='dld') }}"

# expose the docker api (only for dev env) to allow IDE's to add remote interpreters for debugging
docker_daemon_hosts:
  - "tcp://0.0.0.0:2375"
  - "unix:///var/run/docker.sock"

docker_daemon_config:
  debug: true
  default-ulimits:
    nofile:
      Name: "nofile"
      Hard: 1048576
      Soft: 1048576
  registry-mirrors:
    - "http://registry-mirror.library.upenn.int:5000"
  insecure-registries:
    - "http://registry-mirror.library.upenn.int:5000"

skip_firewall: true
skip_docker_group: true
skip_docker_user: true
skip_docker_install: true
skip_docker_repo_setup: true
skip_install_deps: true
skip_docker_config: true
